version: '3'
services:
  develop:
    build: .
    command: make develop
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
volumes:
  nodemodules:
